// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDzjYF_YQT6b8IWZCbAdfgHZC518L-BU',
    appId: '1:924658123972:web:2bd7cc7c3d5fc5cd3f7591',
    messagingSenderId: '924658123972',
    projectId: 'hectoclash0',
    authDomain: 'hectoclash0.firebaseapp.com',
    storageBucket: 'hectoclash0.firebasestorage.app',
    measurementId: 'G-F06RXQ71YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzqFXtDlfA7doec_ctYXypgQGmIkr__jU',
    appId: '1:924658123972:android:a384a5a5aea86e653f7591',
    messagingSenderId: '924658123972',
    projectId: 'hectoclash0',
    storageBucket: 'hectoclash0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC70BVyolDpBA35hJSkw_8d7hscsADIYsw',
    appId: '1:924658123972:ios:1682c129c74083dd3f7591',
    messagingSenderId: '924658123972',
    projectId: 'hectoclash0',
    storageBucket: 'hectoclash0.firebasestorage.app',
    iosBundleId: 'com.example.hectoClash1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC70BVyolDpBA35hJSkw_8d7hscsADIYsw',
    appId: '1:924658123972:ios:1682c129c74083dd3f7591',
    messagingSenderId: '924658123972',
    projectId: 'hectoclash0',
    storageBucket: 'hectoclash0.firebasestorage.app',
    iosBundleId: 'com.example.hectoClash1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRDzjYF_YQT6b8IWZCbAdfgHZC518L-BU',
    appId: '1:924658123972:web:603adc168203dc383f7591',
    messagingSenderId: '924658123972',
    projectId: 'hectoclash0',
    authDomain: 'hectoclash0.firebaseapp.com',
    storageBucket: 'hectoclash0.firebasestorage.app',
    measurementId: 'G-RLQP1HKD7S',
  );

}